algoritmo "MostrarNome"

var
//texto - caractere - string
//verdadeiro/falso - logico - boleano
//numero inteiro - inteiro - int
//numeros decimal - real - float
nomeUsuario : caractere

inicio
//output- saida - telas, leds, resposta por voz, som
// input- entrada - teclado, mouse, microfone
// l - line break - quebra da linha

// nomeUsuario <- "Filipe"
escreva("Digite seu nome: ")
leia(nomeUsuario)
escreva("Oi, ")
escreval("Bom dia" +nomeUsuario)

fimalgoritmo