algoritmo "VETOR"

var
alunos : vetor [1..5] de caractere 


inicio
escreval ("Digite o numero do aluno 1:")
leia (alunos[1])
escreval ("Digite o numero do aluno 2:")
leia (alunos[2])
escreval ("Digite o numero do aluno 3:")
leia (alunos[3])
escreval ("Digite o numero do aluno 4:")
leia (alunos[4])
escreval ("Digite o numero do aluno 5:")
leia (alunos[5])

escreval ( "Os numeros cadastrados sao:" + "alunos[1]", "alunos[2]","alunos[3]","alunos[4]","alunos[5]")
fimalgoritmo